import { Link, Navigate, Route, Routes } from "react-router";
import { useAuth } from "@/hooks/use-auth";
import { PhaseOneWorkspace } from "@/components/dashboard/PhaseOneWorkspace";
import BusinessLayout from "./business/BusinessLayout";
import { BusinessAnalyticsPage, BusinessDashboardPage, BusinessDonationDetailsPage, BusinessDonationsPage, BusinessHelpPage, BusinessImpactPage, BusinessNotificationsPage, BusinessProfilePage, BusinessReportsPage, BusinessReputationPage, BusinessSettingsPage, BusinessSubscriptionPage, BusinessTeamPage, BusinessTrackingPage, BusinessDonatePage } from "./business/BusinessPages";

export default function BusinessRoutes() {
  const { user } = useAuth();
  if (!user || user.role !== "business") return <div className="flex min-h-screen items-center justify-center"><div className="rounded-3xl border border-[#E6EAE4] bg-white p-8 text-center shadow-sm"><ShieldLockIcon /><h1 className="mt-4 text-2xl font-extrabold text-[#173B38]">Access Restricted</h1><p className="mt-2 text-sm text-[#71817C]">This workspace is available only to business accounts.</p><Link to="/dashboard" className="mt-5 inline-block rounded-xl bg-[#0B8B7F] px-4 py-3 text-sm font-bold text-white">Back to dashboard</Link></div></div>;
  return <BusinessLayout><Routes><Route index element={<Navigate to="dashboard" replace />} /><Route path="dashboard" element={<BusinessDashboardPage />} /><Route path="ai-matching" element={<PhaseOneWorkspace role="business" />} /><Route path="profile" element={<BusinessProfilePage />} /><Route path="donate" element={<BusinessDonatePage />} /><Route path="donations" element={<BusinessDonationsPage />} /><Route path="donations/active" element={<BusinessDonationsPage activeOnly />} /><Route path="donations/history" element={<BusinessDonationsPage />} /><Route path="donations/:id" element={<BusinessDonationDetailsPage />} /><Route path="tracking" element={<BusinessTrackingPage />} /><Route path="analytics" element={<BusinessAnalyticsPage />} /><Route path="impact" element={<BusinessImpactPage />} /><Route path="reputation" element={<BusinessReputationPage />} /><Route path="subscription" element={<BusinessSubscriptionPage />} /><Route path="team" element={<BusinessTeamPage />} /><Route path="notifications" element={<BusinessNotificationsPage />} /><Route path="reports" element={<BusinessReportsPage />} /><Route path="help" element={<BusinessHelpPage />} /><Route path="settings" element={<BusinessSettingsPage />} /><Route path="*" element={<Navigate to="/404" replace />} /></Routes></BusinessLayout>;
}
function ShieldLockIcon() { return <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-[#FFF0EB] text-[#C65A35]">!</div>; }
